"""
Data Engineering related words and hints for the Hangman game.
Each entry is a dict with 'word', 'hint', and 'category'.
"""

WORDS = [
    # --- ETL / ELT ---
    {"word": "ETL", "hint": "Extract, Transform, Load — classic data pipeline pattern", "category": "Pipeline"},
    {"word": "ELT", "hint": "Extract, Load, Transform — modern lakehouse pattern", "category": "Pipeline"},
    {"word": "PIPELINE", "hint": "A series of data processing steps", "category": "Pipeline"},
    {"word": "INGESTION", "hint": "The process of bringing data into a system", "category": "Pipeline"},
    {"word": "EXTRACTION", "hint": "Pulling data from source systems", "category": "Pipeline"},
    {"word": "TRANSFORMATION", "hint": "Converting data from one format or structure to another", "category": "Pipeline"},
    {"word": "LOADING", "hint": "Writing processed data into a target system", "category": "Pipeline"},
    {"word": "BATCH", "hint": "Processing data in large groups at scheduled intervals", "category": "Pipeline"},
    {"word": "STREAMING", "hint": "Processing data continuously in real-time", "category": "Pipeline"},
    {"word": "ORCHESTRATION", "hint": "Coordinating and managing complex data workflows", "category": "Pipeline"},
    {"word": "SCHEDULING", "hint": "Running jobs at specific times or intervals", "category": "Pipeline"},
    {"word": "WORKFLOW", "hint": "A defined sequence of tasks in a data process", "category": "Pipeline"},
    {"word": "DAG", "hint": "Directed Acyclic Graph — used in Airflow for task dependencies", "category": "Pipeline"},
    {"word": "IDEMPOTENT", "hint": "Running an operation multiple times gives the same result", "category": "Pipeline"},
    {"word": "BACKFILL", "hint": "Retroactively processing historical data", "category": "Pipeline"},

    # --- Tools & Technologies ---
    {"word": "SPARK", "hint": "Apache distributed computing engine for big data", "category": "Tool"},
    {"word": "KAFKA", "hint": "Distributed event streaming platform by Apache", "category": "Tool"},
    {"word": "AIRFLOW", "hint": "Apache workflow orchestration tool with DAGs", "category": "Tool"},
    {"word": "HADOOP", "hint": "Framework for distributed storage and processing (HDFS + MapReduce)", "category": "Tool"},
    {"word": "HIVE", "hint": "Data warehouse software on top of Hadoop", "category": "Tool"},
    {"word": "FLINK", "hint": "Apache stream processing framework", "category": "Tool"},
    {"word": "DBTOOL", "hint": "Data Build Tool — SQL-based transformation framework (dbt)", "category": "Tool"},
    {"word": "SNOWFLAKE", "hint": "Cloud-native data warehouse platform", "category": "Tool"},
    {"word": "REDSHIFT", "hint": "Amazon's cloud data warehouse service", "category": "Tool"},
    {"word": "BIGQUERY", "hint": "Google Cloud's serverless data warehouse", "category": "Tool"},
    {"word": "DATABRICKS", "hint": "Unified analytics platform built on Spark", "category": "Tool"},
    {"word": "PREFECT", "hint": "Modern Python-based workflow orchestration tool", "category": "Tool"},
    {"word": "DAGSTER", "hint": "Data orchestrator for ML, analytics, and ETL", "category": "Tool"},
    {"word": "NIFI", "hint": "Apache tool for automating data flow between systems", "category": "Tool"},
    {"word": "PRESTO", "hint": "Distributed SQL query engine for big data", "category": "Tool"},
    {"word": "TRINO", "hint": "Fork of Presto — fast distributed SQL engine", "category": "Tool"},
    {"word": "DRUID", "hint": "Real-time analytics database for event-driven data", "category": "Tool"},
    {"word": "DUCKDB", "hint": "In-process SQL OLAP database (like SQLite for analytics)", "category": "Tool"},
    {"word": "FIVETRAN", "hint": "Managed ELT data integration service", "category": "Tool"},
    {"word": "STITCH", "hint": "Cloud-first open-source data integration platform", "category": "Tool"},
    {"word": "TALEND", "hint": "Enterprise data integration and quality tool", "category": "Tool"},
    {"word": "GLUE", "hint": "AWS serverless ETL service", "category": "Tool"},
    {"word": "KINESIS", "hint": "AWS real-time data streaming service", "category": "Tool"},
    {"word": "PUBSUB", "hint": "Google Cloud messaging and streaming service", "category": "Tool"},
    {"word": "TERRAFORM", "hint": "Infrastructure as Code tool by HashiCorp", "category": "Tool"},
    {"word": "DOCKER", "hint": "Containerization platform for packaging applications", "category": "Tool"},
    {"word": "KUBERNETES", "hint": "Container orchestration system (K8s)", "category": "Tool"},
    {"word": "JENKINS", "hint": "Open-source CI/CD automation server", "category": "Tool"},
    {"word": "GRAFANA", "hint": "Open-source monitoring and observability dashboard", "category": "Tool"},
    {"word": "PROMETHEUS", "hint": "Open-source monitoring and alerting toolkit", "category": "Tool"},
    {"word": "ELASTICSEARCH", "hint": "Distributed search and analytics engine", "category": "Tool"},

    # --- Databases & Storage ---
    {"word": "DATABASE", "hint": "An organized collection of structured data", "category": "Storage"},
    {"word": "WAREHOUSE", "hint": "Central repository for integrated data from multiple sources", "category": "Storage"},
    {"word": "DATALAKE", "hint": "Storage repository holding vast amounts of raw data", "category": "Storage"},
    {"word": "LAKEHOUSE", "hint": "Combines data lake and data warehouse features", "category": "Storage"},
    {"word": "DATAMART", "hint": "Subset of a data warehouse for a specific business area", "category": "Storage"},
    {"word": "POSTGRES", "hint": "Popular open-source relational database (PostgreSQL)", "category": "Storage"},
    {"word": "MYSQL", "hint": "Widely used open-source relational database", "category": "Storage"},
    {"word": "MONGODB", "hint": "Popular NoSQL document-oriented database", "category": "Storage"},
    {"word": "CASSANDRA", "hint": "Apache distributed NoSQL database for high availability", "category": "Storage"},
    {"word": "REDIS", "hint": "In-memory key-value data store used for caching", "category": "Storage"},
    {"word": "PARQUET", "hint": "Columnar storage file format optimized for analytics", "category": "Storage"},
    {"word": "AVRO", "hint": "Row-based data serialization format by Apache", "category": "Storage"},
    {"word": "DELTA", "hint": "Open-source storage layer (Delta Lake) with ACID transactions", "category": "Storage"},
    {"word": "ICEBERG", "hint": "Apache open table format for large analytic datasets", "category": "Storage"},
    {"word": "ORC", "hint": "Optimized Row Columnar file format for Hadoop", "category": "Storage"},
    {"word": "HDFS", "hint": "Hadoop Distributed File System", "category": "Storage"},
    {"word": "BLOB", "hint": "Binary Large Object — cloud storage type (Azure Blob)", "category": "Storage"},

    # --- Data Concepts ---
    {"word": "SCHEMA", "hint": "The structure or blueprint of a database or table", "category": "Concept"},
    {"word": "NORMALIZATION", "hint": "Organizing data to reduce redundancy in databases", "category": "Concept"},
    {"word": "DENORMALIZATION", "hint": "Adding redundancy to improve read performance", "category": "Concept"},
    {"word": "PARTITION", "hint": "Dividing a table into smaller, manageable pieces", "category": "Concept"},
    {"word": "SHARDING", "hint": "Splitting data across multiple database instances", "category": "Concept"},
    {"word": "INDEX", "hint": "Data structure to speed up data retrieval", "category": "Concept"},
    {"word": "QUERY", "hint": "A request for data from a database", "category": "Concept"},
    {"word": "JOIN", "hint": "Combining rows from two or more tables", "category": "Concept"},
    {"word": "AGGREGATION", "hint": "Computing summary values (SUM, AVG, COUNT)", "category": "Concept"},
    {"word": "DIMENSION", "hint": "Descriptive attributes in a star schema (who, what, where)", "category": "Concept"},
    {"word": "FACT", "hint": "Measurable event data in a star schema", "category": "Concept"},
    {"word": "STARSCHEMA", "hint": "Data warehouse design with fact and dimension tables", "category": "Concept"},
    {"word": "SNOWFLAKESCHEMA", "hint": "Normalized version of star schema design", "category": "Concept"},
    {"word": "SURROGATE", "hint": "System-generated key replacing natural keys", "category": "Concept"},
    {"word": "METADATA", "hint": "Data that describes other data", "category": "Concept"},
    {"word": "LINEAGE", "hint": "Tracking data origin and transformations over time", "category": "Concept"},
    {"word": "CATALOG", "hint": "Inventory of available data assets in an organization", "category": "Concept"},
    {"word": "GOVERNANCE", "hint": "Policies and processes for managing data availability and quality", "category": "Concept"},
    {"word": "QUALITY", "hint": "Ensuring data is accurate, complete, and consistent", "category": "Concept"},
    {"word": "PROFILING", "hint": "Analyzing data to understand its structure and quality", "category": "Concept"},
    {"word": "CLEANSING", "hint": "Detecting and correcting corrupt or inaccurate data", "category": "Concept"},
    {"word": "DEDUPLICATION", "hint": "Removing duplicate records from a dataset", "category": "Concept"},
    {"word": "SERIALIZATION", "hint": "Converting data objects into a storable format", "category": "Concept"},
    {"word": "LATENCY", "hint": "Time delay between data generation and availability", "category": "Concept"},
    {"word": "THROUGHPUT", "hint": "Amount of data processed in a given time period", "category": "Concept"},
    {"word": "SCALABILITY", "hint": "System's ability to handle growing amounts of data", "category": "Concept"},
    {"word": "REPLICATION", "hint": "Copying data across multiple nodes for redundancy", "category": "Concept"},
    {"word": "CONSISTENCY", "hint": "Ensuring all nodes see the same data at the same time", "category": "Concept"},
    {"word": "AVAILABILITY", "hint": "System remains operational even during failures", "category": "Concept"},
    {"word": "TOLERANCE", "hint": "System continues operating despite network failures (CAP theorem)", "category": "Concept"},
    {"word": "ACID", "hint": "Atomicity, Consistency, Isolation, Durability — transaction properties", "category": "Concept"},
    {"word": "EVENTUAL", "hint": "_____ consistency — data will be consistent given enough time", "category": "Concept"},
    {"word": "UPSERT", "hint": "Update existing or insert new records", "category": "Concept"},
    {"word": "MERGE", "hint": "SQL operation combining INSERT, UPDATE, DELETE", "category": "Concept"},
    {"word": "WINDOW", "hint": "SQL function operating over a set of rows (OVER clause)", "category": "Concept"},
    {"word": "CTE", "hint": "Common Table Expression — temporary named result set in SQL", "category": "Concept"},
    {"word": "SUBQUERY", "hint": "A query nested inside another query", "category": "Concept"},
    {"word": "MATERIALIZED", "hint": "_____ view — precomputed query results stored physically", "category": "Concept"},
    {"word": "CHANGELOG", "hint": "Log of all changes made to data (CDC pattern)", "category": "Concept"},
    {"word": "TOMBSTONE", "hint": "Marker indicating a deleted record in distributed systems", "category": "Concept"},
    {"word": "COMPACTION", "hint": "Merging small files or segments into larger ones", "category": "Concept"},
    {"word": "WATERMARK", "hint": "Mechanism tracking progress in stream processing", "category": "Concept"},

    # --- Architecture & Patterns ---
    {"word": "MICROSERVICES", "hint": "Architecture where application is a collection of small services", "category": "Architecture"},
    {"word": "MONOLITH", "hint": "Single unified application architecture", "category": "Architecture"},
    {"word": "API", "hint": "Application Programming Interface", "category": "Architecture"},
    {"word": "REST", "hint": "Representational State Transfer — API architecture style", "category": "Architecture"},
    {"word": "WEBHOOK", "hint": "HTTP callback triggered by an event", "category": "Architecture"},
    {"word": "LAMBDA", "hint": "Serverless compute or architecture combining batch and stream", "category": "Architecture"},
    {"word": "KAPPA", "hint": "Architecture using only stream processing (no batch layer)", "category": "Architecture"},
    {"word": "MEDALLION", "hint": "Bronze-Silver-Gold data architecture pattern", "category": "Architecture"},
    {"word": "CDC", "hint": "Change Data Capture — tracking changes in source data", "category": "Architecture"},
    {"word": "OLAP", "hint": "Online Analytical Processing — optimized for queries", "category": "Architecture"},
    {"word": "OLTP", "hint": "Online Transaction Processing — optimized for transactions", "category": "Architecture"},
    {"word": "DATAOPS", "hint": "Agile methodology applied to data analytics", "category": "Architecture"},
    {"word": "CICD", "hint": "Continuous Integration / Continuous Deployment", "category": "Architecture"},
    {"word": "OBSERVABILITY", "hint": "Ability to measure internal system states from outputs", "category": "Architecture"},
    {"word": "MONITORING", "hint": "Tracking system performance and health metrics", "category": "Architecture"},
    {"word": "ALERTING", "hint": "Notifying teams when systems behave unexpectedly", "category": "Architecture"},
    {"word": "SLA", "hint": "Service Level Agreement — uptime and quality guarantees", "category": "Architecture"},
    {"word": "FEDERATION", "hint": "Querying multiple data sources as if they were one", "category": "Architecture"},
    {"word": "MESH", "hint": "Data _____ — decentralized data ownership architecture", "category": "Architecture"},

    # --- Cloud & Infrastructure ---
    {"word": "CLOUD", "hint": "On-demand computing resources over the internet", "category": "Cloud"},
    {"word": "AWS", "hint": "Amazon Web Services — leading cloud provider", "category": "Cloud"},
    {"word": "AZURE", "hint": "Microsoft's cloud computing platform", "category": "Cloud"},
    {"word": "GCP", "hint": "Google Cloud Platform", "category": "Cloud"},
    {"word": "SERVERLESS", "hint": "Cloud model where provider manages the infrastructure", "category": "Cloud"},
    {"word": "CLUSTER", "hint": "Group of connected computers working together", "category": "Cloud"},
    {"word": "NODE", "hint": "Single machine in a distributed computing cluster", "category": "Cloud"},
    {"word": "CONTAINER", "hint": "Lightweight, standalone executable package", "category": "Cloud"},
    {"word": "BUCKET", "hint": "Cloud storage container (S3, GCS)", "category": "Cloud"},
    {"word": "REGION", "hint": "Geographic area where cloud resources are hosted", "category": "Cloud"},
    {"word": "VPC", "hint": "Virtual Private Cloud — isolated network in the cloud", "category": "Cloud"},
    {"word": "IAM", "hint": "Identity and Access Management", "category": "Cloud"},

    # --- Data Formats & Languages ---
    {"word": "SQL", "hint": "Structured Query Language — the language of databases", "category": "Language"},
    {"word": "PYTHON", "hint": "Most popular programming language in data engineering", "category": "Language"},
    {"word": "SCALA", "hint": "JVM language commonly used with Apache Spark", "category": "Language"},
    {"word": "JAVA", "hint": "Language used in many big data frameworks", "category": "Language"},
    {"word": "JSON", "hint": "JavaScript Object Notation — lightweight data format", "category": "Language"},
    {"word": "CSV", "hint": "Comma Separated Values — simple tabular file format", "category": "Language"},
    {"word": "XML", "hint": "Extensible Markup Language", "category": "Language"},
    {"word": "YAML", "hint": "Human-readable data serialization format for configs", "category": "Language"},
    {"word": "PROTOBUF", "hint": "Protocol Buffers — Google's data serialization format", "category": "Language"},
    {"word": "REGEX", "hint": "Regular Expression — pattern matching in text", "category": "Language"},

    # --- Data Science / ML Adjacent ---
    {"word": "FEATURE", "hint": "Individual measurable property used in ML models", "category": "ML"},
    {"word": "PANDAS", "hint": "Python library for data manipulation and analysis", "category": "ML"},
    {"word": "DATAFRAME", "hint": "Two-dimensional labeled data structure (Pandas/Spark)", "category": "ML"},
    {"word": "NOTEBOOK", "hint": "Interactive computing environment (Jupyter)", "category": "ML"},
    {"word": "MLOPS", "hint": "DevOps practices applied to machine learning", "category": "ML"},
]
